### ISSUE TITLE
Paths using `\` instead of `/`

### ISSUE THREAD

**Issue by davidfaber** [kallefrombosnia/twill-graphql#9]
In the file `vendor/kallefrombosnia/twill-graphql/src/Commands/DeployCommand.php` on lines 28, 30 and 31 your are using `\` as path-separator instead of `/`.

This works only on windows.

This is also fixed in my fork: https://github.com/perituswebdesign/twill-graphql

**Comment by kallefrombosnia** [comment]
Good catch, this command wasn't covered by tests so I haven't seen an issue in non-win environments.
If it's not a problem, please submit a PR afterward.
